name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FLORIDA }}

      - name: Add DigitalOcean host key to known hosts
        run: ssh-keyscan -H 159.65.220.12 >> ~/.ssh/known_hosts

      - name: Deploy application via SSH
        run: |
          ssh root@159.65.220.12 << 'EOF'
            cd /root/apps/freeroyalties
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
